version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80/tcp"
      - "8843:443/tcp"
    environment:
      TZ: 'Asia/Kolkata' # Replace with your timezone
      WEBPASSWORD: 'YOUR_ADMIN_PASSWORD'
    # Volumes store your data between container upgrades
    volumes:
      - 'YOUR_APP_DATA_PATH/pihole/etc-pihole:/etc/pihole'
      - 'YOUR_APP_DATA_PATH/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
