version: '3.3'
services:
    portainer-ce:
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        restart: always
        environment:
            - PUID=1001
            - PGID=100
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/YOUR_APPDATA_PATH/portainer:/data'
        image: 'portainer/portainer-ce:latest'
